version: "2"
linters:
  settings:
    staticcheck: # https://staticcheck.dev/docs/configuration/options/
      checks: ["all", "-ST1000", "-ST1003", "-ST1005", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
